#!/bin/bash

source timeclock.sh

command=$1;
clockStatus=$(getLastAction)

case "$command" in
	in )
		if [[ $clockStatus == 'OUT' || -z $clockStatus ]]; then
			clockIn "$(getTags "$@")"
		fi
		echo "Nothing happened, you are already clocked in!"
		;;
	out )
		if [[ $clockStatus == 'IN' || -z $clockStatus ]]; then
			clockOut "$(getTags "$@")"
		fi
		echo "Nothing happened, you are already clocked out!"
		;;
	hours )
		calcHours
		;;
	* )
		displayHelp
esac
